slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG

    odom_frame: odom
    map_frame: map
    base_frame: robot_center
    scan_topic: /scan_synced
    use_scan_matching: true
    max_laser_range: 20.0
    min_laser_range: 0.5
    resolution: 0.05
    map_update_interval: 2.0
    use_scan_barycenter: true
    transform_timeout: 1.0

    mode: mapping
