slam_toolbox:
  ros__parameters:
    use_sim_time: false

    odom_frame: odom
    map_frame: map
    base_frame: robot_center
    scan_topic: /scan_synced

    # Carte
    resolution: 0.05
    map_update_interval: 2.0

    # TF
    transform_timeout: 2.5
    tf_buffer_duration: 30.0

    # Seuils de mouvement plus sensibles
    # Avant: 0.2 m et 0.2 rad
    # Maintenant: 2 cm et ~1.1 deg
    minimum_travel_distance: 0.02
    minimum_travel_heading: 0.02

    mode: mapping

    # Paramètres standards utiles
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_start_at_dock: false
